### ISSUE TITLE
Need Jenkin Variable Replacement for 'KeyFile' attribute.

### ISSUE THREAD

**Issue by pshettyk** [thexman/ssh-port-forwarding#2]
I have modified the code of PortForwardingBuildWrapper.java to have Jenkin Variable Replacement for 'KeyFile' attribute.

In method 'setUp'

`final EnvVars envVars = build.getEnvironment(listener);
		final Session session = forwardPorts(logger, envVars);`

In method 'forwardPorts'
`final Session session = createSession(envVars);	`

In method 'createSession'
`private Session createSession(final EnvVars envVars) throws JSchException {
		JSch jsch = new JSch();		
		Session session = jsch.getSession(username, host, port);
		session.setDaemonThread(true);
		if (this.keyfile != null && this.keyfile.length() > 0) {
			jsch.addIdentity(envVars.expand(this.keyfile), this.password);`

But I am not able to commit to git hub. 
Please update the code to have this feature or allow me to commit into feature branch.
Thanks
Prakash

**Comment by thexman** [comment]
Done
